### ISSUE TITLE
Test all the services in the consistent way

### ISSUE THREAD

**Issue by Mikanebu** [datahq/bitstore#13]
We currently have 5 repos (+ deploy) (in Python) with several different ways of running tests.

# Acceptance criteria

- [x] bitstore is tested with tox

Bonus:

- [x] able to install with pip 
- [x] we have Makefile for test and install  
- [x] versioned

# Tasks 

- [x] refactor tests for bitstore
- [x] update README

**Comment by zelima** [comment]
FIXED
