### ISSUE TITLE
Serve endpoint for generating presigned URL if necessary 

### ISSUE THREAD

**Issue by zelima** [datahq/bitstore#17]
We need to serve the API that takes URL, JWT and owner as query parameters (or send URL and owner via body and token as header) and returns signed URL

We might need this to handle not only rawstore, but pkgstore as well  (so maybe we can send service name in as well? Eg: bitstore / metastore - see https://github.com/datahq/bitstore/issues/18) 

## Acceptance Criteria

* [x] https://api.datahub.io/rawstore/checkurl?url=https://rawstore.datahub.io/core/finance-vix&owner=core&jwt=token for generating signed urls 
* [x] If dataset is not private signed URL is not generated 
* [x] no security problems (see analysis)

## Tasks

* [x] serve `/checkurl` endpoint 
* [x] function for handling signed urls as bellow 
* [x] tests
* [x] update README

```
def check_url(token, owner, url):
  needs_signed_url = requests.get(url)
  if needs_signed_url.status_code != 403:
    return {url: url}
  if owner is None:
    return Response(status=400)
  if not services.verify(token, owner):
    return Response(status=401)
  parsed_url = requests.utils.urlparse(url)
  bucket = parsed_url.netloc
  key = parsed_url.path
  signed_url = s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': bucket,
        'Key': key
    }
  return {url: signed_url}
```

### Security problem

Current implementation flow  is following: 
* user sends GET request to the service with token, userid and URL to sign for Eg: https://api.datahub.io/rawstore/signurl?jwt=token&userid=core&url=https://pkgstore.datahub.io/core/finance-vix/data/vix-daily.csv
* System will authenticate User and return signed url. 

**Problem:** This means that any user can send **any** URL and get it signed if they are authenticated. How to make sure that file belongs to him?

**Comment by zelima** [comment]
FIXED. Security problem solved by checking ownerid inside url (that signals that url is owned by owner)
