### ISSUE TITLE
Generate signed URl for S3 for pkgstore as well

### ISSUE THREAD

**Issue by zelima** [datahq/bitstore#18]
As we are introducing Private datasets, we need to be able to access a private object on S3 via signed URLs. We need to do the same exact thing for two storages - rawstore and pkgstore. In order to avoid one more separate service for dealing with generating signed URLs for pkgstore we can re-use same endpoint that is used for rawstore by including "storage" name in request body or query parameter

## Acceptance Criteria

* [ ] able to get signed ULR (if necessary) for both rawstore and pkgstore

## Tasks

* [ ] change env `STORAGE_BUCKET_NAME` to `RAWSTORE_BUCKET_NAME`
* [ ] add new env variable  `PKGSTORE_BUCKET_NAME`
* [ ] await "storage" as quary parameter or as parameter in body 
  * storage='pkgstore'
  * storage='rawstore'
* [ ] decide which bucket to connect according to "storage"
* [ ] generate signed URL  (implemented #17 )
* [ ] tests 
* [ ] update README
* [ ] update Env variables in deploy repo and docker cloud

**Comment by zelima** [comment]
INVALID this is possible without any modification to the bitstore
