### ISSUE TITLE
Remove STORAGE_HOSTNAME

### ISSUE THREAD

**Issue by rufuspollock** [datahq/bitstore#6]
Remove from config and from code as it does not serve any purpose and is confusing.

## Acceptance criteria
* [ ] No STORAGE_HOSTNAME in ENV variables

## Task

* [x] clone the repo and run tests and server locally(make sure everything works fine)
* [x] Read the code and understand it. (search `STORAGE_HOSTNAME` and think what it is used for)
* [x] Remove `STORAGE_HOSTNAME` and run tests and server locally (see what has been broken)
* [ ] Probably fakes3 related tests will be broken
  * [ ] Fix that by changing fake s3 related tests to use `moto` (lib for testing boto https://github.com/spulec/moto)
* [ ] Have passing tests
* [ ] run server locally and make sure everything still works fin
* [ ] Remove `STORAGE_HOSTNAME` from README

/cc @akariv any comments here - is there a reason we have it and make it configurable.
